# HandyHub Admin Service Configuration

app:
  name: "handyhub-admin-svc"
  version: "1.0.0"
  timeout: 10
  host-link: "http://localhost:8002"

logs:
  level: "debug"
  path: "./../logs/sys.log"
  enable-json-output: true

server:
  port: ":8002"
  mode: "debug"
  read-timeout: 30
  write-timeout: 30
  idle-timeout: 60

database:
  url: "mongodb://localhost:27017"
  dbname: "handyhub"
  timeout: 10
  collections:
    users: "users"
    sessions: "sessions"

redis:
  url: "localhost:6379"
  password: ""
  db: 3

messaging:
  rabbitmq:
    url: "amqp://guest:guest@localhost:5672/"
    exchange: "handyhub"
    exchange-type: "topic"
    prefetch-count: 1
    prefetch-size: 0
    global: false
    reconnect-delay: 5
    timeout: 10
    durable: true
    auto-delete: false
    internal: false
    no-wait: false
    exclusive: false
    auto-ack: false
    no-local: false
  queues:
    user-activity:
      name: "user_activity_queue"
      routing-key: "activity.update"
      consumer: "user_activity_consumer"

security:
  jwt-key: "your-secret-jwt-key"

cache:
  expiration-minutes: 60
  session-expiration-minutes: 30
  extended-expiration-minutes: 30
  user-stats:
    key: "user_stats"
    expiration-minutes: 30

search:
  min-query-limit: 20
  max-query-limit: 100

external-services:
  auth-service:
    url: "http://localhost:8001"
    timeout: 10